//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public System.Guid idFlight { get; set; }
        public System.Guid idCompany { get; set; }
        public string name { get; set; }
        public Nullable<int> fDayofWeek { get; set; }
        public System.Guid idCityDeparture { get; set; }
        public System.Guid idCityArrival { get; set; }
        public Nullable<System.TimeSpan> departureTime { get; set; }
        public Nullable<System.TimeSpan> arrivalTime { get; set; }
        public System.Guid idFlightState { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual FlightState FlightState { get; set; }
    }
}
