//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public System.Guid Id { get; set; }
        public System.Guid IdFlight { get; set; }
        public System.Guid IdFlightState { get; set; }
        public Nullable<System.DateTime> DepartureDT { get; set; }
        public Nullable<System.DateTime> ArrivalDT { get; set; }
        public string Comment { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual FlightState FlightState { get; set; }
    }
}
