//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public System.Guid idFlight { get; set; }
        public Nullable<System.Guid> idCompany { get; set; }
        public Nullable<System.Guid> idFStatus { get; set; }
        public Nullable<System.Guid> idDeparture { get; set; }
        public Nullable<System.Guid> idArrival { get; set; }
        public string name { get; set; }
        public Nullable<int> fDayofWeek { get; set; }
    
        public virtual Arrival Arrival { get; set; }
        public virtual Company Company { get; set; }
        public virtual Departure Departure { get; set; }
        public virtual FStatu FStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
